services:
  - type: web
    name: quiz-management-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: quiz-db
    plan: free
    databaseName: quiz_management
    user: quiz_user
